version: "3.8"

services:
  reactivitiesdb:
    container_name: reactivitiesdb
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=ReactivitiesDB
    volumes:
      - postgres_data:/var?lib?postgresql/data/
        
  pgadmin:
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@reactivities.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    volumes:
      - pgadmin_data:/root/.pgadmin